apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-server-mock
spec:
  selector:
    matchLabels:
      app: oidc-server-mock
  template:
    metadata:
      labels:
        app: oidc-server-mock
    spec:
      containers:
      - name: oidc-server-mock
        image: soluto/oidc-server-mock
        imagePullPolicy: Never
        env:
          - name: API_SCOPES_INLINE
            value: |
              [
                "user-service-scope"
              ]
          - name: API_RESOURCES_INLINE
            value: |
              [
                {
                  "Name": "user-service",
                  "Scopes": ["user-service-scope"]
                }
              ]
          - name: CLIENTS_CONFIGURATION_INLINE
            value: |
              [
                {
                    "ClientId": "e2e-client-id",
                    "ClientSecrets": [
                      "e2e-client-secret"
                    ],
                    "Description": "e2e configuration",
                    "AllowedGrantTypes": [
                        "client_credentials"
                    ],
                    "AllowedScopes": [
                        "user-service-scope"
                    ],
                    "ClientClaimsPrefix": "",
                    "Claims": [
                      {
                        "Type": "string_claim",
                        "Value": "string_claim_value"
                      },
                      {
                        "Type": "json_claim",
                        "Value": "['value1', 'value2']",
                        "ValueType": "json"
                      }
                    ]
                }
              ]
        livenessProbe:
          httpGet:
            path: /.well-known/openid-configuration
            port: 80
        resources:
            limits:
                cpu: 1
                memory: 1000M
---
kind: Service
apiVersion: v1
metadata:
  name: oidc-server-mock
spec:
  selector:
    app: oidc-server-mock
  ports:
    - name: http
      port: 80
      targetPort: 80
---