name: PR

on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    paths-ignore:
      - README.md

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install missing dependencies
        run: sudo apt-get install ffmpeg

      - name: install latest buildx
        run: |
          mkdir -p ~/.docker/cli-plugins &&
          wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64 &&
          chmod a+x  ~/.docker/cli-plugins/docker-buildx
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run npm install
        run: npm ci
        working-directory: ./e2e

      - name: Run Tests
        run: npm run test
        working-directory: ./e2e
