name: PR

on:
  pull_request:
    paths-ignore:
      - README.md

  workflow_dispatch:

concurrency:
  group: pr-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  TILT_VERSION: '0.33.17'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Tilt
        uses: yokawasa/action-setup-kube-tools@v0.11.1
        with:
          setup-tools: |
            tilt
          tilt: ${{ env.TILT_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Run npm install
        run: npm ci

      - name: Eslint
        run: npm run lint

      - name: Run Tests
        run: npm run tilt:ci
