name: PR

on:
  pull_request:
    paths-ignore:
      - README.md

  workflow_dispatch:

jobs:
  checks-ubuntu:
    name: Tests
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]
    uses: ./.github/workflows/reusable-pr.yaml
    with:
      runner: ${{ matrix.runner }}
