name: PR

on:
  pull_request:
    paths-ignore:
      - README.md

  workflow_dispatch:

concurrency:
  group: pr-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  TILT_VERSION: '0.33.12'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Tilt
        uses: yokawasa/action-setup-kube-tools@v0.11.0
        with:
          setup-tools: |
            tilt
          tilt: ${{ env.TILT_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run npm install
        run: npm ci

      - name: Eslint
        run: npm run lint

      - name: Run Tests
        run: npm run tilt:ci
